name: PSDO CI/CD Workflow

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
  SERVER_HOST: ${{secrets.SERVER_HOST}}
  SERVER_USER: ${{secrets.SERVER_USER}}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      di_tag_main: ${{ steps.di_tag_main.outputs.DI_TAG_MAIN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image and push Docker image to Docker Hub
        id: di_tag_main
        run: |
          DI_TAG_MAIN="main-$(date +%s)"
          docker buildx build . --file Dockerfile --push --platform linux/amd64 -t $DOCKER_USERNAME/pdso-challenge-01:$DI_TAG_MAIN
          echo "DI_TAG_MAIN=$DI_TAG_MAIN" >> $GITHUB_OUTPUT

      - name: Log out from Docker Hub
        run: docker logout
    
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_HOST }}
          port: 22
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY}}
          script: |
            sudo docker rm -f my-simple-webapp || true
            sudo docker run -d -p 80:8080 -e PORT=8080 --name=my-simple-webapp ${{ env.DOCKER_USERNAME }}/pdso-challenge-01:${{needs.build.outputs.di_tag_main}}
