---

- name: Update DNS Records
  uri:
    url: https://api.godaddy.com/v1/domains/senyumku.com/records/A/dev-api-app-logs/
    method: PUT
    body_format: json
    headers:
      Authorization: sso-key AQN1hqXG71e_BA25udmxKUyMRjX4K4j6cT:NiodNgYs5MbjNi5KcJjaCH
    body:
      data: "string"
      port: 0
      priority: 0
      protocol: "string"
      service: "string"
      ttl: 0
      weight: 0
  register: _dnsList

- debug:
    msg: "{{_dnsList}}"