---

general:
  prefix_first: "rcloud"
  prefix_second: "labs"
  region_default: "us-west1"
  wild_world_range: "0.0.0.0/0"
project:
  - projectID: "devops-project-253405" 
    authkind: "serviceaccount"
#   Leave another blank if you involving one project only
#  - projectID: "" 
#    authkind: ""
serviceaccounts: 
  - name: "devops-ansible"
    email: "devops-ansible@devops-project-253405.iam.gserviceaccount.com"
    json_directory: "files/serviceaccounts/"
    json_name: "devops-project-253405-4cf109d08c9e.json"
users:
  ssh:
    - username: "rivan_amarbank"
      pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhiHWyHv+ZJ34vb3yV/ifp7ma8d4lvBViyeVDS4074d48lb+ya3O9oletZXexEyv3pXDtW1gXQIHRZr/Qh0h8TwSTKo+29Obp9QDbP3Nmwp12llDbMiYuXGn7McpuhWUYvW8zTSfPVBNBKtUKf+JiAf3Z4vCYkcAJKx5Xg3Zf2lmwF41E1EJIRAY0qSb87rbDSmyRhdQHhS4aUsLvxGhSYTuf+gh8ohgAPmdAqBU728Waf85l2xUGq4BJMt7EsZWMvOmowtVGJdj4cXH26CtoDgFF5DzL4CPFdztQpNKs5f31SXfhpUNlY7EpZ0jkoNeF5xQf/5EwNt22gbxlHUNwCw=="
      key_directory: "files/ssh_keys/"
      key_filename: "rivan_amar.pem"
vpc:
  name: "rcloud-labs-vpc-01"
subnets:
  - name: "rcloud-labs-vpc-01-west1-subnet-01"
    group: "west1"
    subnet_range: "172.25.0.0/22"
vms:
  - cluster_name: "rancher-k8s"
    properties:
      - role: "master"
        index: "01"
        zone: "a"
        type: "e2-medium"
        state: "present"
        disk1_size: "20"
        firewall_tags: ["allow-ssh-public","allow-webports-public"]
        images: "https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20201112"
        # images: "https://www.googleapis.com/compute/v1/projects/devops-project-253405/global/images/rancheros-image" # rancheros
      - role: "etcd-controlplane"
        index: "01"
        zone: "b"
        type: "e2-medium"
        state: "present"
        disk1_size: "20"
        firewall_tags: ["allow-ssh-public","allow-webports-public"]
        images: "https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20201112"
      - role: "worker"
        index: "01"
        zone: "a"
        type: "e2-medium"
        state: "present"
        disk1_size: "20"
        firewall_tags: ["allow-ssh-public","allow-webports-public"]
        images: "https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20201112"
      - role: "worker"
        index: "02"
        zone: "b"
        type: "e2-small"
        state: "present"
        disk1_size: "20"
        firewall_tags: ["allow-ssh-public","allow-webports-public"]
        images: "https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20201112"
