---

- hosts: localhost
  become: yes
  vars_files:
    - vars/dbs.yml
  tasks: 
    - name: Activate service account
      shell: gcloud auth activate-service-account "{{postgres.sa_name}}"  --key-file="{{postgres.sa_file_loc}}" --project="{{postgres.project_name}}"

    - name:  Select service account
      shell: gcloud config set account "{{postgres.sa_name}}"
      
    - name: Restore databases 
      shell: gcloud sql databases create "{{csql_db_name.db_name}}" --instance="{{postgres.instance_name}}" --charset="UTF8" --collation="en_US.UTF8" --project="{{postgres.project_name}}"
    #  shell: gcloud sql databases delete "{{csql_db_name.db_name}}" --instance="{{postgres.instance_name}}" --project="{{postgres.project_name}}"
      with_items: "{{postgres.dbs}}"
      loop_control:
        loop_var: csql_db_name
